import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/ui/layout/NavBar";
import { Container } from "@/components/ui/layout/Container";
import { SocketContextProvider } from '@/context/SocketContext'
import { Toaster } from 'sonner'
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "VideoChat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={cn(geistSans.variable, geistMono.variable, 'antialiased relative overflow-x-hidden')}>
          <SocketContextProvider>
            <main className="flex min-h-screen flex-col bg-secondary">
              <Navbar />
              <Container>{children}</Container>
            </main>
            <Toaster position="top-right" />
          </SocketContextProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
